Project Backup

diff --git a/install_qcd b/install_qcd
--- a/install_qcd
+++ b/install_qcd
@@ -6,7 +6,6 @@ QCD_FOLD=~/.qcd
 QCD_PROG=./qcd.sh
 QCD_LICE=./LICENSE
 QCD_READ=./README.md
-QCD_STOR=~/.qcd/store
 
 read -p "Please Confirm Installation of QCD [y/n]: " confirm
 
@@ -20,6 +19,9 @@ then
     elif [[ -f ~/.bash_profile ]]
     then
       echo -e "\nqcd() {\n  . ~/.qcd/qcd.sh \$1\n}\n\nqcd" >> ~/.bash_profile
+    else
+      echo -e "ERROR: Failed to Add Command To Terminal Config. Aborting Installation."
+      exit 1
     fi
 
     echo -e "→ Installed QCD Command To Terminal Config"
@@ -31,11 +33,6 @@ then
   command mv $QCD_READ $QCD_FOLD
 
   echo -e "→ Installed QCD In ~/.qcd"
-
-  if [[ ! -f $QCD_STOR ]]
-  then
-    touch $QCD_STOR
-  fi
 
   echo -e "\nQCD Successfully Installed, Please Restart Your Terminal!"
 elif [ $confirm == n ] || [ $confirm == N ]
